/**
 * Hand Logger — narration log.
 *
 * Keeps what each narration attempt actually produced: what was transcribed or
 * read off an image, what the parser understood, which questions it asked, and
 * what the player changed before handing off to the wizard. Without it a failed
 * real-world attempt (a noisy table, a mis-heard card) leaves nothing behind to
 * learn from — the endpoints answer and forget.
 *
 * Text only: the audio and image files themselves are never stored.
 *
 * Fire-and-forget by design. Logging must never slow down or break the request
 * it describes, so the insert is not awaited and a failure only reaches the
 * server log.
 */

const pool = require('../config/db');

const SESSION_RE = /^[A-Za-z0-9_-]{1,64}$/;
const MAX_TEXT = 20000;        // a long narration is a few hundred characters
const MAX_DETAILS = 200000;    // state + gaps of one parse is a few KB

const clip = (s) => (s == null ? null : String(s).slice(0, MAX_TEXT));

/**
 * @param {import('express').Request} req - supplies the user and the session header
 * @param {object} entry
 * @param {'transcribe'|'read_image'|'parse'|'recheck'|'handoff'} entry.kind
 * @param {string} [entry.input]  - what went in (typed/transcribed text, file description)
 * @param {string} [entry.output] - text that came out (transcript, text read off an image)
 * @param {object} [entry.details] - structured result (state, gaps, contradictions…)
 * @param {string} [entry.error]
 * @param {number} [entry.startedAt] - Date.now() when the request began
 */
function logNarration(req, { kind, input = null, output = null, details = {}, error = null, startedAt = null }) {
  // One id per narration attempt, generated by the client, ties the transcribe /
  // parse / recheck / handoff calls for the same hand together.
  const header = typeof req.get === 'function' ? req.get('x-narration-session') : null;
  const sessionId = header && SESSION_RE.test(header) ? header : null;

  let json;
  try { json = JSON.stringify(details ?? {}); } catch { json = '{}'; }
  if (json.length > MAX_DETAILS) json = JSON.stringify({ truncated: true, bytes: json.length });

  pool.query(
    `INSERT INTO hand_narration_logs
       (user_id, session_id, kind, input_text, output_text, details, error, duration_ms)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8)`,
    [req.user?.id ?? null, sessionId, kind, clip(input), clip(output), json, clip(error),
     startedAt ? Date.now() - startedAt : null]
  ).catch(err => console.error('[NarrationLog] insert failed:', err.message));
}

module.exports = { logNarration };
